# Only used for local development
services:
  postgres:
    image: pgautoupgrade/pgautoupgrade:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

